import Link from "next/link";
import { ArrowRight, CalendarRange, Plus } from "lucide-react";
import { PageHeader } from "@/components/dashboard/app-shell";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { EmptyState } from "@/components/dashboard/empty-state";
import { Card } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/server";

export default async function SessionsPage(){const supabase=await createClient();const{data:sessions}=await supabase.from("feedback_sessions").select("id,title,description,status,expected_responses,created_at,courses(name,code)").order("created_at",{ascending:false});return <><PageHeader eyebrow="Feedback lifecycle" title="Sessions" description="Move from draft questions to open feedback, reflection, and evidence-grounded analysis." action={<Link href="/dashboard/sessions/new" className="focus-ring inline-flex h-11 items-center gap-2 rounded-xl bg-[#184f43] px-4 text-sm font-semibold text-white"><Plus size={16}/>New session</Link>}/>{sessions?.length?<div className="grid gap-4 lg:grid-cols-2">{sessions.map(session=><Card key={session.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-[#267865]">{session.courses?.code}</p><h2 className="mt-1 text-xl font-bold">{session.title}</h2></div><StatusBadge status={session.status}/></div><p className="mt-3 line-clamp-2 min-h-10 text-sm leading-5 text-[#71807a]">{session.description||session.courses?.name}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-xs text-[#84908c]">Expected: {session.expected_responses??"Not set"}</span><Link href={`/dashboard/sessions/${session.id}`} className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-semibold text-[#267865]">Open workspace <ArrowRight size={15}/></Link></div></Card>)}</div>:<EmptyState icon={CalendarRange} title="No feedback sessions" description="Create a focused session for a lecture, lab, or course activity." action={<Link href="/dashboard/sessions/new" className="font-semibold text-[#267865]">Create the first session</Link>}/>}</>}
