import Link from "next/link";
import { ArrowRight, BarChart3, BrainCircuit, Check, FileLock2, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "@/components/brand/logo";

const features = [
  { icon: ShieldCheck, title: "Anonymous by design", copy: "One-time hashed codes prevent reuse without asking students for names, emails, or accounts." },
  { icon: BarChart3, title: "Signals, not spreadsheets", copy: "See response progress, rating distributions, choices, and written feedback in one clear view." },
  { icon: BrainCircuit, title: "Reflection-aware AI", copy: "Combine class feedback with your own reflection and teaching materials for five actionable insights." },
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f6f3eb]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Logo /><div className="flex items-center gap-2"><Link className="focus-ring rounded-xl px-4 py-2 text-sm font-semibold text-[#42524d]" href="/session/demo">Student access</Link><Link className="focus-ring rounded-xl bg-[#184f43] px-4 py-2 text-sm font-semibold text-white" href="/login">Instructor login</Link></div></nav>
    <section className="paper-grid relative border-y">
      <div className="absolute -right-32 -top-32 size-96 rounded-full bg-[#ed765f]/10 blur-3xl" />
      <div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:py-28">
        <div className="relative z-10 animate-rise"><div className="inline-flex items-center gap-2 rounded-full border bg-white/80 px-3 py-1.5 text-sm font-semibold text-[#184f43]"><Sparkles size={15} /> Better feedback conversations</div><h1 className="balance mt-7 max-w-3xl text-5xl font-bold leading-[1.04] tracking-[-.055em] sm:text-6xl lg:text-7xl">Hear the room.<br/><span className="text-[#267865]">Improve the next one.</span></h1><p className="balance mt-6 max-w-2xl text-lg leading-8 text-[#5f6e69]">SignalRoom helps instructors collect truly anonymous course feedback, make sense of patterns, and turn reflection into practical teaching improvements.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="focus-ring inline-flex h-12 items-center gap-2 rounded-xl bg-[#184f43] px-5 font-semibold text-white shadow-[0_12px_30px_rgba(24,79,67,.22)]">Open instructor workspace <ArrowRight size={18} /></Link><a href="#how" className="focus-ring inline-flex h-12 items-center rounded-xl border bg-white px-5 font-semibold text-[#184f43]">See how it works</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[#66756f]">{["No student accounts", "Private PDF storage", "Five structured insights"].map((item) => <span key={item} className="flex items-center gap-1.5"><Check className="text-[#267865]" size={15} />{item}</span>)}</div></div>
        <div className="relative mx-auto w-full max-w-xl animate-rise [animation-delay:120ms]"><div className="absolute -left-6 top-12 h-32 w-32 rotate-[-8deg] rounded-[2rem] bg-[#ed765f]"/><div className="relative rounded-[2rem] border bg-[#fffdf8] p-5 shadow-[0_32px_80px_rgba(28,59,51,.16)] sm:p-7"><div className="flex items-center justify-between border-b pb-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#7a8883]">Live session</p><h2 className="mt-1 font-bold">Unit testing & automation</h2></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">Open</span></div><div className="mt-6 grid grid-cols-3 gap-3">{[["Responses","14 / 20"],["Completion","70%"],["Avg. clarity","4.3"]].map(([label,value]) => <div key={label} className="rounded-2xl bg-[#f2f3ee] p-3"><p className="text-xs text-[#74817d]">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</div><div className="mt-6"><div className="flex items-center justify-between text-sm"><span className="font-semibold">Learning objectives were clear</span><span className="font-bold text-[#267865]">4.5</span></div><div className="mt-3 flex h-24 items-end gap-2">{[18,28,42,70,92].map((height,index) => <div key={height} className="flex-1 rounded-t-lg bg-[#267865]" style={{ height: `${height}%`, opacity: .36 + index * .14 }} />)}</div><div className="mt-2 flex justify-between text-[10px] text-[#81908b]">{[1,2,3,4,5].map(n => <span key={n}>{n}</span>)}</div></div><div className="mt-6 flex items-start gap-3 rounded-2xl border border-[#eadbb9] bg-[#fff8e5] p-4"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#f2d789] text-[#6e5319]"><BrainCircuit size={18}/></span><div><p className="text-sm font-bold">Insight preview</p><p className="mt-1 text-sm leading-5 text-[#6b6250]">Students value live examples; protect practice time by moving setup material before class.</p></div></div></div></div>
      </div>
    </section>
    <section id="how" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#267865]">Designed for honest learning</p><h2 className="balance mt-3 text-3xl font-bold tracking-[-.04em] sm:text-4xl">Feedback with enough structure to act on—and enough privacy to trust.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(({icon:Icon,title,copy},i) => <article key={title} className="rounded-2xl border bg-[#fffdf8] p-6 shadow-[0_12px_36px_rgba(31,64,55,.05)]"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#e3f0eb] text-[#184f43]"><Icon size={21}/></span><span className="font-mono text-xs text-[#9aa49f]">0{i+1}</span></div><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66756f]">{copy}</p></article>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="noise relative overflow-hidden rounded-[2rem] bg-[#173f37] px-6 py-12 text-white sm:px-12"><FileLock2 className="absolute right-10 top-8 size-40 rotate-12 text-white/5"/><div className="relative max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#9dd2c4]">Privacy, stated plainly</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">Anonymous means we don’t ask who they are.</h2><p className="mt-4 leading-7 text-white/70">A response code can be used once. SignalRoom does not claim to prove that one physical person submitted only once—doing that would require student identification.</p></div></div></section>
    <footer className="border-t bg-[#fffdf8]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-[#6f7b77] sm:flex-row sm:items-center sm:justify-between sm:px-8"><Logo/><p>Built for thoughtful instructors and honest classrooms.</p></div></footer>
  </main>;
}
