"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, Save } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Label, Textarea } from "@/components/ui/field";

type Reflection = { perceived_strengths:string; perceived_challenges:string; surprises:string; next_steps:string } | null;
export function ReflectionForm({sessionId,initial,enabled}:{sessionId:string;initial:Reflection;enabled:boolean}){const[loading,setLoading]=useState(false);const router=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const f=new FormData(e.currentTarget);const response=await fetch(`/api/sessions/${sessionId}/reflection`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({perceivedStrengths:f.get("strengths"),perceivedChallenges:f.get("challenges"),surprises:f.get("surprises"),nextSteps:f.get("nextSteps")})});const result=await response.json();setLoading(false);if(!response.ok)return toast.error(result.error);toast.success("Reflection saved");router.refresh();}return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="strengths">What worked well?</Label><Textarea id="strengths" name="strengths" defaultValue={initial?.perceived_strengths} disabled={!enabled} required minLength={10}/></div><div><Label htmlFor="challenges">What felt challenging?</Label><Textarea id="challenges" name="challenges" defaultValue={initial?.perceived_challenges} disabled={!enabled} required minLength={10}/></div><div><Label htmlFor="surprises">What surprised you?</Label><Textarea id="surprises" name="surprises" defaultValue={initial?.surprises} disabled={!enabled} required minLength={10}/></div><div><Label htmlFor="nextSteps">What will you try next?</Label><Textarea id="nextSteps" name="nextSteps" defaultValue={initial?.next_steps} disabled={!enabled} required minLength={10}/></div><div className="sm:col-span-2"><Button disabled={!enabled||loading}>{loading?<LoaderCircle className="animate-spin" size={16}/>:<Save size={16}/>}Save reflection</Button></div></form>}
